name: build

on:
  push:
    branches:
      - master
      - main
    tags:
      - 'v*'
  pull_request:


jobs:

  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      
    - name: Test
      run: |
        go mod tidy -v
        go test -race ./...

    - name: Lint
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1.1"
        install-go: false

    - name: Build
      run: go build ./...

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      # only release on tags
      if: success() && startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.FAILLINT_ACTIONS_BOT_TOKEN }}
